
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:47:24.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/jenkins/triggers/ReverseBuildTrigger.java , [318:29~324:30]
   core/src/main/java/hudson/tasks/BuildTrigger.java , [448:29~452:30]

*/


package hudson.tasks;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import hudson.model.Job;

public final class ExtractedSeparateClass89208 {
    private ExtractedSeparateClass89208() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod10484(final Job <?, ?> p, final Logger LOGGER, final String oldFullName, final String newFullName) {
        try {
            p.save();
        } catch (IOException e) {
            LOGGER.log(Level.WARNING,
                    "Failed to persist project setting during rename from " + oldFullName + " to "
                            + newFullName, e);
        }
    }
}
