
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:47:57.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/lib/layout/ConfirmationLinkTest.java , [174:9~176:44]
   test/src/test/java/lib/layout/StopButtonTest.java , [118:9~120:44]

*/


package lib.layout;

import com.gargoylesoftware.htmlunit.html.DomNodeList;
import com.gargoylesoftware.htmlunit.html.HtmlAnchor;
import com.gargoylesoftware.htmlunit.html.HtmlElement;
import com.gargoylesoftware.htmlunit.html.HtmlPage;
import static org.junit.Assert.assertEquals;

public final class ExtractedSeparateClass52589 {
    private ExtractedSeparateClass52589() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static HtmlAnchor getVar87000(final HtmlPage page) {
        DomNodeList<HtmlElement> anchors = page.getElementById("test-panel").getElementsByTagName("a");
        assertEquals(1, anchors.size());
        return (HtmlAnchor) anchors.get(0);
    }
}
