
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:03:06.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/lib/layout/LayoutTest.java , [42:9~52:10]
   test/src/test/java/lib/layout/AjaxTest.java , [46:9~56:10]

*/


package lib.layout;

import java.io.IOException;
import com.gargoylesoftware.htmlunit.html.DomElement;
import com.gargoylesoftware.htmlunit.html.HtmlLink;
import org.jvnet.hudson.test.JenkinsRule;
import org.xml.sax.SAXException;

public final class ExtractedSeparateClass40402 {
    private ExtractedSeparateClass40402() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod82684(final JenkinsRule r) throws IOException, SAXException {
        JenkinsRule.WebClient wc = r.createWebClient();
        String prefix = r.contextPath + '/';
        for (DomElement e : wc.goTo("login").getElementsByTagName("link")) {
            String href = ((HtmlLink) e).getHrefAttribute();
            if (!href.startsWith(prefix)) {
                System.err.println("ignoring " + href);
                continue;
            }
            System.err.println("checking " + href);
            wc.goTo(href.substring(prefix.length()), null);
        }
    }
}
