
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:49:31.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/hudson/model/BooleanParameterDefinition.java , [114:9~117:26]
   core/src/main/java/hudson/model/TextParameterDefinition.java , [92:9~95:26]
   core/src/main/java/hudson/model/StringParameterDefinition.java , [183:9~186:26]
   core/src/main/java/hudson/model/ChoiceParameterDefinition.java , [193:9~196:26]
   core/src/main/java/hudson/model/ParameterDefinition.java , [265:9~268:26]
   core/src/main/java/hudson/model/PasswordParameterDefinition.java , [127:9~130:26]
   core/src/main/java/hudson/model/RunParameterDefinition.java , [230:9~233:26]

*/


package hudson.model;

import java.util.Objects;

public final class ExtractedSeparateClass40378 {
    private ExtractedSeparateClass40378() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static Boolean getVar85851(final ParameterDefinition other, ParameterDefinition this_) {
        if (!Objects.equals(this_.getName(), other.getName()))
            return false;
        if (!Objects.equals(this_.getDescription(), other.getDescription()))
            return false;
        return null;
    }
}
