
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:04:22.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/hudson/model/MultiStageTimeSeries.java , [269:13~274:47]
   core/src/main/java/hudson/model/LoadStatistics.java , [242:9~247:43]

*/


package hudson.model;

import hudson.util.NoOverlapCategoryAxis;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.plot.CategoryPlot;

public final class ExtractedSeparateClass34761 {
    private ExtractedSeparateClass34761() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static CategoryAxis getDomainAxis86582(final CategoryPlot plot) {
        final CategoryAxis domainAxis = new NoOverlapCategoryAxis(null);
        plot.setDomainAxis(domainAxis);
        domainAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_90);
        domainAxis.setLowerMargin(0.0);
        domainAxis.setUpperMargin(0.0);
        domainAxis.setCategoryMargin(0.0);
        return domainAxis;
    }
}
