
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:45:49.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/hudson/model/LoadStatistics.java , [243:9~249:71]
   core/src/main/java/hudson/model/Job.java , [1494:17~1500:79]

*/


package hudson.model;

import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;

public final class ExtractedSeparateClass98293 {
    private ExtractedSeparateClass98293() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static NumberAxis getRangeAxis92805(final CategoryPlot plot, final CategoryAxis domainAxis) {
        plot.setDomainAxis(domainAxis);
        domainAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_90);
        domainAxis.setLowerMargin(0.0);
        domainAxis.setUpperMargin(0.0);
        domainAxis.setCategoryMargin(0.0);
        
        final NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        return rangeAxis;
    }
}
