
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:02:07.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/DeleteBuildsCommandTest.java , [296:9~300:42]
   test/src/test/java/hudson/cli/DeleteBuildsCommandTest.java , [246:9~250:42]
   test/src/test/java/hudson/cli/DeleteBuildsCommandTest.java , [180:9~184:42]
   test/src/test/java/jenkins/model/GlobalBuildDiscarderTest.java , [92:13~96:41]
   test/src/test/java/jenkins/model/GlobalBuildDiscarderTest.java , [41:13~45:40]

*/


package jenkins.model;

import hudson.model.FreeStyleProject;
import org.jvnet.hudson.test.JenkinsRule;

public final class ExtractedSeparateClass81877 {
    private ExtractedSeparateClass81877() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod9883(final JenkinsRule j, final FreeStyleProject project) throws Exception {
        j.buildAndAssertSuccess(project);
        j.buildAndAssertSuccess(project);
        j.buildAndAssertSuccess(project);
        j.buildAndAssertSuccess(project);
        j.buildAndAssertSuccess(project);
    }
}
