
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:46:01.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/DeleteBuildsCommandTest.java , [246:9~251:42]
   test/src/test/java/jenkins/model/GlobalBuildDiscarderTest.java , [92:13~97:41]

*/


package jenkins.model;

import hudson.model.FreeStyleProject;
import org.jvnet.hudson.test.JenkinsRule;

public final class ExtractedSeparateClass81834 {
    private ExtractedSeparateClass81834() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod95206(final JenkinsRule j, final FreeStyleProject project) throws Exception {
        j.buildAndAssertSuccess(project);
        j.buildAndAssertSuccess(project);
        j.buildAndAssertSuccess(project);
        j.buildAndAssertSuccess(project);
        j.buildAndAssertSuccess(project);
        j.buildAndAssertSuccess(project);
    }
}
