
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:02:46.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/hudson/model/Descriptor.java , [437:17~441:35]
   core/src/main/java/hudson/util/FormValidation.java , [607:21~611:37]

*/


package hudson;

import java.util.List;
import hudson.util.ReflectionUtils.Parameter;

public final class ExtractedSeparateClass16038 {
    private ExtractedSeparateClass16038() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod51454(final Parameter p, String name, final List<String> depends) {
        RelativePath rp = p.annotation(RelativePath.class);
        if (rp!=null)
            name = rp.value()+'/'+name;
        
        depends.add(name);
    }
}
