
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:02:43.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/hudson/console/ConsoleAnnotatorFactory.java , [90:9~93:33]
   core/src/main/java/hudson/model/Descriptor.java , [192:17~195:41]

*/


package hudson;

import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import org.jvnet.tiger_types.Types;

public final class ExtractedSeparateClass98603 {
    private ExtractedSeparateClass98603() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static Class getVar50543(final Type type) {
        if (type instanceof ParameterizedType)
            return Types.erasure(Types.getTypeArgument(type,0));
        else
            return Object.class;
    }
}
