
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:53:19.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/hudson/FilePath.java , [3654:9~3665:59]
   core/src/main/java/hudson/FilePath.java , [3634:13~3645:63]

*/


package hudson;

import java.io.IOException;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;

public final class ExtractedSeparateClass9632 {
    private ExtractedSeparateClass9632() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static Path getVar59216(final Path path, final Logger LOGGER) throws IOException {
        try {
            return path.toRealPath();
        }
        catch (IOException e) {
            if (LOGGER.isLoggable(Level.FINE)) {
                LOGGER.log(Level.FINE, String.format("relaxedToRealPath cannot use the regular toRealPath on %s, trying with toRealPath(LinkOption.NOFOLLOW_LINKS)", path), e);
            }
        }
        
        // that's required for specific environment like Windows Server 2016, running MSFT docker
        // where the root is a <SYMLINKD>
        return path.toRealPath(LinkOption.NOFOLLOW_LINKS);
    }
}
