
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:04:13.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/hudson/lifecycle/SolarisSMFLifecycle.java , [45:9~52:10]
   core/src/main/java/hudson/lifecycle/WindowsServiceLifecycle.java , [120:9~127:10]
   core/src/main/java/hudson/lifecycle/ExitLifecycle.java , [65:9~73:10]
   core/src/main/java/hudson/WebAppMain.java , [438:13~445:14]
   core/src/main/java/hudson/lifecycle/UnixLifecycle.java , [67:9~74:10]

*/


package hudson;

import java.util.logging.Level;
import java.util.logging.Logger;
import jenkins.model.Jenkins;

public final class ExtractedSeparateClass94655 {
    private ExtractedSeparateClass94655() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod14973(final Logger LOGGER) {
        Jenkins jenkins = Jenkins.getInstanceOrNull(); // guard against repeated concurrent calls to restart
        
        try {
            if (jenkins != null) {
                jenkins.cleanUp();
            }
        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, "Failed to clean up. Restart will continue.", e);
        }
    }
}
