
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:04:42.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/hudson/PluginManager.java , [2397:9~2400:21]
   core/src/main/java/hudson/model/UpdateCenter.java , [2626:9~2629:21]
   core/src/main/java/hudson/logging/LogRecorderManager.java , [213:9~216:21]

*/


package hudson;

import hudson.model.AbstractModelObject;
import jenkins.model.Jenkins;
import org.springframework.security.access.AccessDeniedException;

public final class ExtractedSeparateClass76418 {
    private ExtractedSeparateClass76418() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static Object getThis5405(final boolean SKIP_PERMISSION_CHECK, AbstractModelObject this_) throws AccessDeniedException {
        if (!SKIP_PERMISSION_CHECK) {
            Jenkins.get().checkPermission(Jenkins.SYSTEM_READ);
        }
        return this_;
    }
}
