
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:45:53.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/jenkins/security/apitoken/ApiTokenStatsRestartTest.java , [163:9~167:75]
   test/src/test/java/jenkins/security/apitoken/ApiTokenStatsTest.java , [121:9~125:75]

*/


package jenkins.security.apitoken;

import java.io.IOException;
import com.gargoylesoftware.htmlunit.xml.XmlPage;
import org.jvnet.hudson.test.JenkinsRule.WebClient;
import org.xml.sax.SAXException;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.xml.HasXPath.hasXPath;

public final class ExtractedSeparateClass61966 {
    private ExtractedSeparateClass61966() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod23619(final WebClient wc, final String username) throws IOException, SAXException {
        XmlPage xmlPage = wc.goToXml("whoAmI/api/xml");
        assertThat(xmlPage, hasXPath("//name", is(username)));
        assertThat(xmlPage, hasXPath("//anonymous", is("false")));
        assertThat(xmlPage, hasXPath("//authenticated", is("true")));
        assertThat(xmlPage, hasXPath("//authority", is("authenticated")));
    }
}
