
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 26-05-2021 09:49:54.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/jenkins/model/lazy/BuildReferenceMapAdapter.java , [322:13~326:22]
   core/src/main/java/jenkins/model/lazy/BuildReferenceMapAdapter.java , [219:13~223:22]

*/


package jenkins.model.lazy;

import java.util.Collection;

public final class ExtractedSeparateClass92378 {
    private ExtractedSeparateClass92378() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static <T0> boolean isB9011(final Collection<?> c, T0 this_) {
        boolean b=false;
        for (Object o : c) {
            b|=this_.remove(o);
        }
        return b;
    }
}
