
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:53:13.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/jenkins/security/stapler/StaplerAbstractTest.java , [132:9~136:35]
   test/src/test/java/jenkins/security/stapler/CustomRoutingDecisionProviderTest.java , [97:9~101:35]

*/


package jenkins.security.stapler;

import java.io.IOException;
import org.kohsuke.stapler.Stapler;
import org.kohsuke.stapler.StaplerResponse;

public final class ExtractedSeparateClass75946 {
    private ExtractedSeparateClass75946() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod63812() {
        StaplerResponse resp = Stapler.getCurrentResponse();
        try {
            resp.getWriter().write("ok");
            resp.flushBuffer();
        } catch (IOException e) {}
    }
}
