
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 04:58:49.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java , [723:9~725:51]
   test/src/test/java/hudson/security/TokenBasedRememberMeServices2Test.java , [148:9~151:43]
   test/src/test/java/hudson/security/TokenBasedRememberMeServices2Test.java , [178:13~181:47]

*/


package hudson.security;

import org.jvnet.hudson.test.JenkinsRule;

public final class ExtractedSeparateClass22399 {
    private ExtractedSeparateClass22399() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static HudsonPrivateSecurityRealm getSecurityRealm58136(final JenkinsRule j) {
        j.jenkins.setDisableRememberMe(false);
        
        HudsonPrivateSecurityRealm realm = new HudsonPrivateSecurityRealm(false, false, null);
        j.jenkins.setSecurityRealm(realm);
        return realm;
    }
}
