
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:03:53.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/hudson/views/MyViewsTabBar.java , [85:9~92:23]
   core/src/main/java/hudson/views/ViewsTabBar.java , [85:9~92:23]

*/


package hudson.views;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import hudson.model.View;

public final class ExtractedSeparateClass55698 {
    private ExtractedSeparateClass55698() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static List<View> getResult868(final List<? extends View> views) {
        List<View> result = new ArrayList<>(views);
        result.sort(new Comparator<View>() {
            @Override
            public int compare(View o1, View o2) {
                return o1.getDisplayName().compareTo(o2.getDisplayName());
            }
        });
        return result;
    }
}
