
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 04:58:50.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/jenkins/telemetry/TelemetryTest.java , [235:13~240:26]
   test/src/test/java/jenkins/telemetry/MissingClassTelemetryTest.java , [116:13~121:26]

*/


package jenkins.telemetry;

import java.io.IOException;
import javax.servlet.FilterChain;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public final class ExtractedSeparateClass81766 {
    private ExtractedSeparateClass81766() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static boolean isVar37973(final HttpServletRequest request, final FilterChain chain, final HttpServletResponse response) throws IOException, ServletException {
        String pathInfo = request.getPathInfo();
        if (pathInfo != null && pathInfo.startsWith("/uplink")) {
            chain.doFilter(request, response);
            return true;
        }
        return false;
    }
}
