
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:03:58.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/RunRangeCommand2Test.java , [89:9~92:10]
   test/src/test/java/hudson/cli/ConsoleCommandTest.java , [285:9~288:10]
   test/src/test/java/hudson/cli/ConsoleCommandTest.java , [212:9~215:10]

*/


package hudson.cli;

import hudson.model.FreeStyleProject;

public final class ExtractedSeparateClass8810 {
    private ExtractedSeparateClass8810() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod34017(final FreeStyleProject project) throws InterruptedException {
        while(!project.isBuilding()) {
            System.out.println("Waiting for build to start and sleep 1s...");
            Thread.sleep(1000);
        }
    }
}
