
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:01:51.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/AddJobToViewCommandTest.java , [91:9~93:83]
   test/src/test/java/hudson/cli/RemoveJobFromViewCommandTest.java , [84:9~86:84]

*/


package hudson.cli;

import hudson.model.FreeStyleProject;
import org.jvnet.hudson.test.JenkinsRule;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public final class ExtractedSeparateClass47814 {
    private ExtractedSeparateClass47814() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod29716(final FreeStyleProject project1, final FreeStyleProject project2, final JenkinsRule j) {
        assertThat(j.jenkins.getView("aView").getAllItems().size(), equalTo(0));
        assertThat(j.jenkins.getView("aView").contains(project1), equalTo(false));
        assertThat(j.jenkins.getView("aView").contains(project2), equalTo(false));
    }
}
