
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:07:34.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [330:9~339:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [300:9~309:74]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [162:9~171:74]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [192:9~201:74]

*/


package hudson.cli;

import hudson.slaves.DumbSlave;
import org.jvnet.hudson.test.JenkinsRule;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public final class ExtractedSeparateClass13654 {
    private ExtractedSeparateClass13654() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static DumbSlave getSlave387190(final JenkinsRule j, final DumbSlave slave1, final DumbSlave slave2) throws Exception {
        DumbSlave slave3 = j.createSlave("aNode3", "", null);
        slave1.toComputer().waitUntilOnline();
        assertThat(slave1.toComputer().isOnline(), equalTo(true));
        assertThat(slave1.toComputer().getOfflineCause(), equalTo(null));
        slave2.toComputer().waitUntilOnline();
        assertThat(slave2.toComputer().isOnline(), equalTo(true));
        assertThat(slave2.toComputer().getOfflineCause(), equalTo(null));
        slave3.toComputer().waitUntilOnline();
        assertThat(slave3.toComputer().isOnline(), equalTo(true));
        assertThat(slave3.toComputer().getOfflineCause(), equalTo(null));
        return slave3;
    }
}
