
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:02:13.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/ConnectNodeCommandTest.java , [176:9~188:62]
   test/src/test/java/hudson/cli/OnlineNodeCommandTest.java , [289:9~301:62]

*/


package hudson.cli;

import hudson.model.Computer;
import jenkins.model.Jenkins;
import org.jvnet.hudson.test.JenkinsRule;
import static hudson.cli.CLICommandInvoker.Matcher.succeededSilently;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public final class ExtractedSeparateClass1588 {
    private ExtractedSeparateClass1588() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod84984(final JenkinsRule j, final CLICommandInvoker command) {
        final Computer masterComputer = j.jenkins.getComputer("");
        
        CLICommandInvoker.Result result = command
                .authorizedTo(Computer.CONNECT, Jenkins.READ)
                .invokeWithArgs("");
        assertThat(result, succeededSilently());
        assertThat(masterComputer.isOnline(), equalTo(true));
        
        result = command
                .authorizedTo(Computer.CONNECT, Jenkins.READ)
                .invokeWithArgs("");
        assertThat(result, succeededSilently());
        assertThat(masterComputer.isOnline(), equalTo(true));
    }
}
