
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:47:57.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/AddJobToViewCommandTest.java , [100:9~102:83]
   test/src/test/java/hudson/cli/RemoveJobFromViewCommandTest.java , [75:9~77:82]

*/


package hudson.cli;

import hudson.model.FreeStyleProject;
import org.jvnet.hudson.test.JenkinsRule;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public final class ExtractedSeparateClass83245 {
    private ExtractedSeparateClass83245() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod4751(final FreeStyleProject project1, final FreeStyleProject project2, final JenkinsRule j) {
        assertThat(j.jenkins.getView("aView").getAllItems().size(), equalTo(2));
        assertThat(j.jenkins.getView("aView").contains(project1), equalTo(true));
        assertThat(j.jenkins.getView("aView").contains(project2 ), equalTo(true));
    }
}
