
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:05:52.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [86:9~88:66]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [123:9~125:66]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [107:9~109:66]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [181:9~183:66]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [143:9~145:66]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [217:9~219:66]

*/


package hudson.cli;

import hudson.slaves.DumbSlave;
import org.jvnet.hudson.test.JenkinsRule;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public final class ExtractedSeparateClass92042 {
    private ExtractedSeparateClass92042() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static DumbSlave getSlave86232(final JenkinsRule j) throws Exception {
        DumbSlave slave = j.createSlave("aNode", "", null);
        slave.toComputer().waitUntilOnline();
        assertThat(slave.toComputer().isOnline(), equalTo(true));
        return slave;
    }
}
