
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:04:04.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/GetNodeCommandTest.java , [99:9~101:51]
   test/src/test/java/hudson/cli/UpdateNodeCommandTest.java , [109:9~111:51]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import static hudson.cli.CLICommandInvoker.Matcher.failedWith;
import static hudson.cli.CLICommandInvoker.Matcher.hasNoStandardOutput;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;

public final class ExtractedSeparateClass57233 {
    private ExtractedSeparateClass57233() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod67815(final CLICommandInvoker.Result result) {
        assertThat(result.stderr(), containsString("No such node ''"));
        assertThat(result, failedWith(3));
        assertThat(result, hasNoStandardOutput());
    }
}
