
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:45:49.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [236:9~238:109]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [132:9~134:108]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [400:9~402:109]

*/


package hudson.cli;

import hudson.slaves.DumbSlave;
import hudson.slaves.OfflineCause;
import hudson.slaves.OfflineCause.ByCLI;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.instanceOf;

public final class ExtractedSeparateClass72017 {
    private ExtractedSeparateClass72017() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod65677(final DumbSlave slave1) {
        assertThat(slave1.toComputer().isOffline(), equalTo(true));
        assertThat(slave1.toComputer().getOfflineCause(), instanceOf(OfflineCause.ByCLI.class));
        assertThat(((OfflineCause.ByCLI) slave1.toComputer().getOfflineCause()).message, equalTo("aCause"));
    }
}
