
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 04:58:45.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/DeleteNodeCommandTest.java , [87:9~89:92]
   test/src/test/java/hudson/cli/WaitNodeOnlineCommandTest.java , [67:9~69:92]
   test/src/test/java/hudson/cli/WaitNodeOfflineCommandTest.java , [67:9~69:92]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import static hudson.cli.CLICommandInvoker.Matcher.failedWith;
import static hudson.cli.CLICommandInvoker.Matcher.hasNoStandardOutput;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;

public final class ExtractedSeparateClass59022 {
    private ExtractedSeparateClass59022() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod39379(final CLICommandInvoker.Result result) {
        assertThat(result, failedWith(3));
        assertThat(result, hasNoStandardOutput());
        assertThat(result.stderr(), containsString("ERROR: No such node 'never_created'"));
    }
}
