
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:06:26.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [370:9~375:97]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [396:9~401:97]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [232:9~237:97]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import hudson.slaves.DumbSlave;
import hudson.slaves.OfflineCause;
import static hudson.cli.CLICommandInvoker.Matcher.failedWith;
import static hudson.cli.CLICommandInvoker.Matcher.hasNoStandardOutput;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.instanceOf;

public final class ExtractedSeparateClass60037 {
    private ExtractedSeparateClass60037() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod81020(final CLICommandInvoker.Result result, final DumbSlave slave1) {
        assertThat(result, failedWith(5));
        assertThat(result, hasNoStandardOutput());
        assertThat(result.stderr(), containsString("never_created: No such agent \"never_created\" exists. Did you mean \"aNode1\"?"));
        assertThat(result.stderr(), containsString("ERROR: " + CLICommand.CLI_LISTPARAM_SUMMARY_ERROR_TEXT));
        assertThat(slave1.toComputer().isOffline(), equalTo(true));
        assertThat(slave1.toComputer().getOfflineCause(), instanceOf(OfflineCause.ByCLI.class));
    }
}
