
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:04:23.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/ConnectNodeCommandTest.java , [57:9~64:108]
   test/src/test/java/hudson/cli/OnlineNodeCommandTest.java , [72:9~79:108]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import jenkins.model.Jenkins;
import org.jvnet.hudson.test.JenkinsRule;
import static hudson.cli.CLICommandInvoker.Matcher.failedWith;
import static hudson.cli.CLICommandInvoker.Matcher.hasNoStandardOutput;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;

public final class ExtractedSeparateClass65223 {
    private ExtractedSeparateClass65223() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static CLICommandInvoker.Result getResult68532(final JenkinsRule j, final CLICommandInvoker command) throws Exception {
        j.createSlave("aNode", "", null);
        
        final CLICommandInvoker.Result result = command
                .authorizedTo(Jenkins.READ)
                .invokeWithArgs("aNode");
        assertThat(result, failedWith(6));
        assertThat(result, hasNoStandardOutput());
        assertThat(result.stderr(), containsString("ERROR: user is missing the Agent/Connect permission"));
        return result;
    }
}
