
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:05:12.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/ConnectNodeCommandTest.java , [91:9~94:47]
   test/src/test/java/hudson/cli/ConnectNodeCommandTest.java , [119:9~122:47]
   test/src/test/java/hudson/cli/OnlineNodeCommandTest.java , [148:9~150:47]

*/


package hudson.cli;

import hudson.slaves.DumbSlave;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public final class ExtractedSeparateClass22535 {
    private ExtractedSeparateClass22535() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod4136(final DumbSlave slave) throws InterruptedException {
        assertThat(slave.toComputer().isOnline(), equalTo(true));
        
        slave.toComputer().disconnect();
        slave.toComputer().waitUntilOffline();
    }
}
