
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:01:48.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/EnablePluginCommandTest.java , [67:9~69:26]
   test/src/test/java/hudson/cli/DisablePluginCommandTest.java , [357:9~359:26]

*/


package hudson.cli;

import java.io.IOException;
import hudson.PluginWrapper;
import org.jvnet.hudson.test.JenkinsRule;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.notNullValue;

public final class ExtractedSeparateClass66855 {
    private ExtractedSeparateClass66855() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod62121(final JenkinsRule j, final String name) throws IOException {
        PluginWrapper plugin = j.getPluginManager().getPlugin(name);
        assertThat(plugin, is(notNullValue()));
        plugin.disable();
    }
}
