
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:05:17.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [422:9~428:105]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [314:9~320:105]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [176:9~182:105]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import hudson.slaves.DumbSlave;
import hudson.slaves.OfflineCause;
import hudson.slaves.OfflineCause.ByCLI;
import static hudson.cli.CLICommandInvoker.Matcher.succeededSilently;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.instanceOf;

public final class ExtractedSeparateClass43427 {
    private ExtractedSeparateClass43427() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod44828(final CLICommandInvoker.Result result, final DumbSlave slave1, final DumbSlave slave2) {
        assertThat(result, succeededSilently());
        assertThat(slave1.toComputer().isOffline(), equalTo(true));
        assertThat(slave1.toComputer().getOfflineCause(), instanceOf(OfflineCause.ByCLI.class));
        assertThat(((OfflineCause.ByCLI) slave1.toComputer().getOfflineCause()).message, equalTo(null));
        assertThat(slave2.toComputer().isOffline(), equalTo(true));
        assertThat(slave2.toComputer().getOfflineCause(), instanceOf(OfflineCause.ByCLI.class));
        assertThat(((OfflineCause.ByCLI) slave2.toComputer().getOfflineCause()).message, equalTo(null));
    }
}
