
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:47:24.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/GetViewCommandTest.java , [93:9~95:111]
   test/src/test/java/hudson/cli/DeleteViewCommandTest.java , [110:9~112:111]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import static hudson.cli.CLICommandInvoker.Matcher.failedWith;
import static hudson.cli.CLICommandInvoker.Matcher.hasNoStandardOutput;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;

public final class ExtractedSeparateClass91295 {
    private ExtractedSeparateClass91295() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod69885(final CLICommandInvoker.Result result) {
        assertThat(result, failedWith(3));
        assertThat(result, hasNoStandardOutput());
        assertThat(result.stderr(), containsString("ERROR: No view named never_created inside view Jenkins"));
    }
}
