
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 04:58:37.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/ViewManipulationTestBase.java , [97:9~99:109]
   test/src/test/java/hudson/cli/UpdateViewCommandTest.java , [66:9~68:109]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import static hudson.cli.CLICommandInvoker.Matcher.failedWith;
import static hudson.cli.CLICommandInvoker.Matcher.hasNoStandardOutput;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;

public final class ExtractedSeparateClass58425 {
    private ExtractedSeparateClass58425() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod37897(final CLICommandInvoker.Result result) {
        assertThat(result, failedWith(6));
        assertThat(result, hasNoStandardOutput());
        assertThat(result.stderr(), containsString("ERROR: user is missing the View/Configure permission"));
    }
}
