
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:47:09.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/RunRangeCommand2Test.java , [109:9~115:55]
   test/src/test/java/hudson/cli/DeleteBuildsCommandTest.java , [157:9~161:125]
   test/src/test/java/hudson/cli/ConsoleCommandTest.java , [317:9~322:125]

*/


package hudson.cli;

import java.io.IOException;
import hudson.model.FreeStyleProject;
import hudson.model.labels.LabelAtom;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public final class ExtractedSeparateClass98970 {
    private ExtractedSeparateClass98970() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod18923(final FreeStyleProject project) throws IOException, InterruptedException {
        project.setAssignedLabel(new LabelAtom("never_created"));
        assertThat("Job wasn't scheduled properly", project.scheduleBuild(0), equalTo(true));
        Thread.sleep(1000);
        assertThat("Job wasn't scheduled properly - it isn't in the queue",
                project.isInQueue(), equalTo(true));
        assertThat("Job wasn't scheduled properly - it is running on non-exist node",
                project.isBuilding(), equalTo(false));
    }
}
