
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:07:31.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [196:9~198:74]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [248:9~250:74]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [222:9~224:74]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [100:9~102:73]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [124:9~126:73]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [166:9~168:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [301:9~303:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [363:9~365:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [435:9~437:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [389:9~391:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [331:9~333:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [415:9~417:74]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [87:9~89:73]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [225:9~227:74]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [163:9~165:74]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [251:9~253:74]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [193:9~195:74]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [137:9~139:73]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [438:9~440:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [334:9~336:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [360:9~362:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [386:9~388:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [412:9~414:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [304:9~306:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [144:9~146:73]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [218:9~220:73]

*/


package hudson.cli;

import hudson.slaves.DumbSlave;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public final class ExtractedSeparateClass25057 {
    private ExtractedSeparateClass25057() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod10074(final DumbSlave slave2) throws InterruptedException {
        slave2.toComputer().waitUntilOnline();
        assertThat(slave2.toComputer().isOnline(), equalTo(true));
        assertThat(slave2.toComputer().getOfflineCause(), equalTo(null));
    }
}
