
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:49:37.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [78:9~81:115]
   test/src/test/java/hudson/cli/ConnectNodeCommandTest.java , [72:9~75:115]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [84:9~87:115]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import static hudson.cli.CLICommandInvoker.Matcher.failedWith;
import static hudson.cli.CLICommandInvoker.Matcher.hasNoStandardOutput;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.not;

public final class ExtractedSeparateClass12048 {
    private ExtractedSeparateClass12048() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod27819(final CLICommandInvoker.Result result) {
        assertThat(result, failedWith(3));
        assertThat(result, hasNoStandardOutput());
        assertThat(result.stderr(), containsString("ERROR: No such agent \"never_created\" exists."));
        assertThat(result.stderr(), not(containsString("ERROR: " + CLICommand.CLI_LISTPARAM_SUMMARY_ERROR_TEXT)));
    }
}
