
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:05:05.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/GetNodeCommandTest.java , [103:9~105:51]
   test/src/test/java/hudson/cli/UpdateNodeCommandTest.java , [113:9~115:51]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import static hudson.cli.CLICommandInvoker.Matcher.failedWith;
import static hudson.cli.CLICommandInvoker.Matcher.hasNoStandardOutput;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;

public final class ExtractedSeparateClass66568 {
    private ExtractedSeparateClass66568() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod1230(final CLICommandInvoker.Result result) {
        assertThat(result.stderr(), containsString("No such node '(master)'"));
        assertThat(result, failedWith(3));
        assertThat(result, hasNoStandardOutput());
    }
}
