
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:01:53.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/AddJobToViewCommandTest.java , [71:9~80:49]
   test/src/test/java/hudson/cli/RemoveJobFromViewCommandTest.java , [53:9~62:49]

*/


package hudson.cli;

import java.io.IOException;
import hudson.model.DirectlyModifiableView;
import hudson.model.FreeStyleProject;
import hudson.model.Job;
import hudson.model.View;
import jenkins.model.Jenkins;
import org.jvnet.hudson.test.JenkinsRule;
import static hudson.cli.CLICommandInvoker.Matcher.succeededSilently;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public final class ExtractedSeparateClass99591 {
    private ExtractedSeparateClass99591() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod40424(final FreeStyleProject project, final CLICommandInvoker command, final JenkinsRule j) throws IOException {
        ((DirectlyModifiableView) j.jenkins.getView("aView")).add(project);
        
        assertThat(j.jenkins.getView("aView").getAllItems().size(), equalTo(1));
        assertThat(j.jenkins.getView("aView").contains(project), equalTo(true));
        
        final CLICommandInvoker.Result result = command
                .authorizedTo(Jenkins.READ, View.READ, Job.READ, View.CONFIGURE)
                .invokeWithArgs("aView", "aProject");
        
        assertThat(result, succeededSilently());
    }
}
