
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:02:23.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/ConnectNodeCommandTest.java , [142:9~144:67]
   test/src/test/java/hudson/cli/OnlineNodeCommandTest.java , [240:9~242:67]

*/


package hudson.cli;

import hudson.slaves.DumbSlave;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public final class ExtractedSeparateClass18056 {
    private ExtractedSeparateClass18056() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod10484(final DumbSlave slave1, final DumbSlave slave2, final DumbSlave slave3) {
        assertThat(slave1.toComputer().isOnline(), equalTo(true));
        assertThat(slave2.toComputer().isOnline(), equalTo(true));
        assertThat(slave3.toComputer().isOnline(), equalTo(true));
    }
}
