
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:05:37.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [206:9~209:109]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [131:9~134:108]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [258:9~261:109]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [445:9~448:109]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [344:9~347:109]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import hudson.slaves.DumbSlave;
import hudson.slaves.OfflineCause;
import hudson.slaves.OfflineCause.ByCLI;
import static hudson.cli.CLICommandInvoker.Matcher.succeededSilently;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.instanceOf;

public final class ExtractedSeparateClass49943 {
    private ExtractedSeparateClass49943() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod75968(final CLICommandInvoker.Result result, final DumbSlave slave1) {
        assertThat(result, succeededSilently());
        assertThat(slave1.toComputer().isOffline(), equalTo(true));
        assertThat(slave1.toComputer().getOfflineCause(), instanceOf(OfflineCause.ByCLI.class));
        assertThat(((OfflineCause.ByCLI) slave1.toComputer().getOfflineCause()).message, equalTo("aCause"));
    }
}
