
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:04:48.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/RemoveJobFromViewCommandTest.java , [93:9~96:81]
   test/src/test/java/hudson/cli/AddJobToViewCommandTest.java , [71:9~74:81]

*/


package hudson.cli;

import java.io.IOException;
import hudson.model.DirectlyModifiableView;
import hudson.model.FreeStyleProject;
import org.jvnet.hudson.test.JenkinsRule;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public final class ExtractedSeparateClass28196 {
    private ExtractedSeparateClass28196() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod69100(final FreeStyleProject project, final JenkinsRule j) throws IOException {
        ((DirectlyModifiableView) j.jenkins.getView("aView")).add(project);
        
        assertThat(j.jenkins.getView("aView").getAllItems().size(), equalTo(1));
        assertThat(j.jenkins.getView("aView").contains(project), equalTo(true));
    }
}
