
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:06:25.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [258:9~260:97]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [94:9~96:96]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [206:9~208:97]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [144:9~146:96]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [152:9~154:96]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [131:9~133:96]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [107:9~109:96]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [115:9~117:96]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [176:9~178:97]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [344:9~346:97]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [445:9~447:97]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [422:9~424:97]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [314:9~316:97]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import hudson.slaves.DumbSlave;
import hudson.slaves.OfflineCause;
import static hudson.cli.CLICommandInvoker.Matcher.succeededSilently;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.instanceOf;

public final class ExtractedSeparateClass27553 {
    private ExtractedSeparateClass27553() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod54153(final CLICommandInvoker.Result result, final DumbSlave slave1) {
        assertThat(result, succeededSilently());
        assertThat(slave1.toComputer().isOffline(), equalTo(true));
        assertThat(slave1.toComputer().getOfflineCause(), instanceOf(OfflineCause.ByCLI.class));
    }
}
