
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:06:00.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/OnlineNodeCommandTest.java , [209:9~216:43]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [257:9~264:43]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [286:9~293:43]

*/


package hudson.cli;

import java.util.concurrent.Future;
import hudson.model.FreeStyleBuild;
import hudson.model.FreeStyleProject;
import hudson.util.OneShotEvent;
import org.jvnet.hudson.test.JenkinsRule;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.hasSize;

public final class ExtractedSeparateClass94054 {
    private ExtractedSeparateClass94054() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod13406(final JenkinsRule j, final FreeStyleProject project, final OneShotEvent finish, final Future<FreeStyleBuild> build) throws Exception {
        assertThat(((FreeStyleProject) j.jenkins.getItem("aProject")).getBuilds(), hasSize(1));
        assertThat(project.isBuilding(), equalTo(true));
        
        finish.signal();
        build.get();
        assertThat(((FreeStyleProject) j.jenkins.getItem("aProject")).getBuilds(), hasSize(1));
        assertThat(project.isBuilding(), equalTo(false));
        j.assertBuildStatusSuccess(build);
    }
}
