
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:47:30.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/GetNodeCommandTest.java , [90:9~92:51]
   test/src/test/java/hudson/cli/UpdateNodeCommandTest.java , [100:9~102:51]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import static hudson.cli.CLICommandInvoker.Matcher.failedWith;
import static hudson.cli.CLICommandInvoker.Matcher.hasNoStandardOutput;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;

public final class ExtractedSeparateClass86636 {
    private ExtractedSeparateClass86636() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod90304(final CLICommandInvoker.Result result) {
        assertThat(result.stderr(), containsString("ERROR: No such node 'MySlave'"));
        assertThat(result, failedWith(3));
        assertThat(result, hasNoStandardOutput());
    }
}
