
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:06:25.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/DeleteJobCommandTest.java , [101:9~103:91]
   test/src/test/java/hudson/cli/RunRangeCommandTest.java , [91:9~93:91]
   test/src/test/java/hudson/cli/SetBuildDescriptionCommandTest.java , [117:9~119:91]
   test/src/test/java/hudson/cli/DeleteBuildsCommandTest.java , [88:9~90:91]
   test/src/test/java/hudson/cli/ConsoleCommandTest.java , [104:9~106:91]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import static hudson.cli.CLICommandInvoker.Matcher.failedWith;
import static hudson.cli.CLICommandInvoker.Matcher.hasNoStandardOutput;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;

public final class ExtractedSeparateClass64147 {
    private ExtractedSeparateClass64147() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod50733(final CLICommandInvoker.Result result) {
        assertThat(result, failedWith(3));
        assertThat(result, hasNoStandardOutput());
        assertThat(result.stderr(), containsString("ERROR: No such job 'never_created'"));
    }
}
