
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:02:48.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [232:9~235:110]
   test/src/test/java/hudson/cli/ConnectNodeCommandTest.java , [155:9~158:110]
   test/src/test/java/hudson/cli/OnlineNodeCommandTest.java , [252:9~255:110]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [370:9~373:110]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [396:9~399:110]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import static hudson.cli.CLICommandInvoker.Matcher.failedWith;
import static hudson.cli.CLICommandInvoker.Matcher.hasNoStandardOutput;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;

public final class ExtractedSeparateClass26107 {
    private ExtractedSeparateClass26107() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod76075(final CLICommandInvoker.Result result) {
        assertThat(result, failedWith(5));
        assertThat(result, hasNoStandardOutput());
        assertThat(result.stderr(), containsString("never_created: No such agent \"never_created\" exists. Did you mean \"aNode1\"?"));
        assertThat(result.stderr(), containsString("ERROR: " + CLICommand.CLI_LISTPARAM_SUMMARY_ERROR_TEXT));
    }
}
