
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:49:43.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [400:9~405:109]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [446:9~451:109]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [345:9~350:109]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [236:9~241:109]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [207:9~212:109]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [259:9~264:109]

*/


package hudson.cli;

import hudson.slaves.DumbSlave;
import hudson.slaves.OfflineCause;
import hudson.slaves.OfflineCause.ByCLI;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.instanceOf;

public final class ExtractedSeparateClass95993 {
    private ExtractedSeparateClass95993() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod54540(final DumbSlave slave1, final DumbSlave slave2) {
        assertThat(slave1.toComputer().isOffline(), equalTo(true));
        assertThat(slave1.toComputer().getOfflineCause(), instanceOf(OfflineCause.ByCLI.class));
        assertThat(((OfflineCause.ByCLI) slave1.toComputer().getOfflineCause()).message, equalTo("aCause"));
        assertThat(slave2.toComputer().isOffline(), equalTo(true));
        assertThat(slave2.toComputer().getOfflineCause(), instanceOf(OfflineCause.ByCLI.class));
        assertThat(((OfflineCause.ByCLI) slave2.toComputer().getOfflineCause()).message, equalTo("aCause"));
    }
}
