
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:02:10.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/jenkins/model/JenkinsManagePermissionTest.java , [95:9~97:40]
   test/src/test/java/hudson/cli/EnablePluginCommandTest.java , [61:9~63:40]
   test/src/test/java/hudson/cli/DisablePluginCommandTest.java , [378:9~380:40]

*/


package hudson.cli;

import hudson.PluginWrapper;
import org.jvnet.hudson.test.JenkinsRule;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.notNullValue;
import static org.junit.Assert.assertTrue;

public final class ExtractedSeparateClass20549 {
    private ExtractedSeparateClass20549() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod78528(final JenkinsRule j, final String name) {
        PluginWrapper plugin = j.getPluginManager().getPlugin(name);
        assertThat(plugin, is(notNullValue()));
        assertTrue(plugin.isEnabled());
    }
}
