
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 04:58:51.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/ViewManipulationTestBase.java , [83:9~85:86]
   test/src/test/java/hudson/cli/DeleteJobCommandTest.java , [78:9~80:86]
   test/src/test/java/hudson/cli/SetBuildDescriptionCommandTest.java , [69:9~71:86]
   test/src/test/java/hudson/cli/DeleteBuildsCommandTest.java , [68:9~70:86]
   test/src/test/java/hudson/cli/ConsoleCommandTest.java , [75:9~77:86]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import static hudson.cli.CLICommandInvoker.Matcher.failedWith;
import static hudson.cli.CLICommandInvoker.Matcher.hasNoStandardOutput;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;

public final class ExtractedSeparateClass31155 {
    private ExtractedSeparateClass31155() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod9084(final CLICommandInvoker.Result result) {
        assertThat(result, failedWith(3));
        assertThat(result, hasNoStandardOutput());
        assertThat(result.stderr(), containsString("ERROR: No such job 'aProject'"));
    }
}
