
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:00:52.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/ReloadConfigurationCommandTest.java , [78:9~80:106]
   test/src/test/java/hudson/cli/ClearQueueCommandTest.java , [61:9~63:106]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import static hudson.cli.CLICommandInvoker.Matcher.failedWith;
import static hudson.cli.CLICommandInvoker.Matcher.hasNoStandardOutput;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;

public final class ExtractedSeparateClass45570 {
    private ExtractedSeparateClass45570() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod18069(final CLICommandInvoker.Result result) {
        assertThat(result, failedWith(6));
        assertThat(result, hasNoStandardOutput());
        assertThat(result.stderr(), containsString("user is missing the Overall/Administer permission"));
    }
}
