
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:51:07.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [94:9~97:104]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [176:9~179:105]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [314:9~317:105]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [422:9~425:105]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import hudson.slaves.DumbSlave;
import hudson.slaves.OfflineCause;
import hudson.slaves.OfflineCause.ByCLI;
import static hudson.cli.CLICommandInvoker.Matcher.succeededSilently;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.instanceOf;

public final class ExtractedSeparateClass56798 {
    private ExtractedSeparateClass56798() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod72217(final CLICommandInvoker.Result result, final DumbSlave slave) {
        assertThat(result, succeededSilently());
        assertThat(slave.toComputer().isOffline(), equalTo(true));
        assertThat(slave.toComputer().getOfflineCause(), instanceOf(OfflineCause.ByCLI.class));
        assertThat(((OfflineCause.ByCLI) slave.toComputer().getOfflineCause()).message, equalTo(null));
    }
}
