
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:49:38.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/EnablePluginCommandTest.java , [73:9~75:41]
   test/src/test/java/hudson/cli/DisablePluginCommandTest.java , [372:9~374:41]

*/


package hudson.cli;

import hudson.PluginWrapper;
import org.jvnet.hudson.test.JenkinsRule;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.notNullValue;
import static org.junit.Assert.assertFalse;

public final class ExtractedSeparateClass36657 {
    private ExtractedSeparateClass36657() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod36202(final JenkinsRule j, final String name) {
        PluginWrapper plugin = j.getPluginManager().getPlugin(name);
        assertThat(plugin, is(notNullValue()));
        assertFalse(plugin.isEnabled());
    }
}
