
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:00:40.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/ViewManipulationTestBase.java , [69:9~71:104]
   test/src/test/java/hudson/cli/GetViewCommandTest.java , [66:9~68:104]
   test/src/test/java/hudson/cli/DeleteViewCommandTest.java , [85:9~87:104]

*/


package hudson.cli;

import hudson.cli.CLICommandInvoker.Result;
import static hudson.cli.CLICommandInvoker.Matcher.failedWith;
import static hudson.cli.CLICommandInvoker.Matcher.hasNoStandardOutput;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;

public final class ExtractedSeparateClass1259 {
    private ExtractedSeparateClass1259() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod18696(final CLICommandInvoker.Result result) {
        assertThat(result, failedWith(6));
        assertThat(result, hasNoStandardOutput());
        assertThat(result.stderr(), containsString("ERROR: user is missing the View/Read permission"));
    }
}
