
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:51:08.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/ConnectNodeCommandTest.java , [93:9~96:67]
   test/src/test/java/hudson/cli/ConnectNodeCommandTest.java , [121:9~124:67]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [221:9~224:67]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [147:9~150:67]

*/


package hudson.cli;

import hudson.slaves.DumbSlave;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public final class ExtractedSeparateClass95734 {
    private ExtractedSeparateClass95734() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod83068(final DumbSlave slave) throws InterruptedException {
        slave.toComputer().disconnect();
        slave.toComputer().waitUntilOffline();
        assertThat(slave.toComputer().isOnline(), equalTo(false));
        assertThat(slave.toComputer().isOffline(), equalTo(true));
    }
}
