
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:05:33.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [374:9~379:105]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [315:9~320:105]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [423:9~428:105]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [177:9~182:105]

*/


package hudson.cli;

import hudson.slaves.DumbSlave;
import hudson.slaves.OfflineCause;
import hudson.slaves.OfflineCause.ByCLI;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.instanceOf;

public final class ExtractedSeparateClass79488 {
    private ExtractedSeparateClass79488() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod65181(final DumbSlave slave1, final DumbSlave slave2) {
        assertThat(slave1.toComputer().isOffline(), equalTo(true));
        assertThat(slave1.toComputer().getOfflineCause(), instanceOf(OfflineCause.ByCLI.class));
        assertThat(((OfflineCause.ByCLI) slave1.toComputer().getOfflineCause()).message, equalTo(null));
        assertThat(slave2.toComputer().isOffline(), equalTo(true));
        assertThat(slave2.toComputer().getOfflineCause(), instanceOf(OfflineCause.ByCLI.class));
        assertThat(((OfflineCause.ByCLI) slave2.toComputer().getOfflineCause()).message, equalTo(null));
    }
}
