
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:05:22.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [386:9~391:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [435:9~440:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [412:9~417:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [360:9~365:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [301:9~306:74]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [331:9~336:74]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [163:9~168:74]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [222:9~227:74]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [248:9~253:74]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [193:9~198:74]

*/


package hudson.cli;

import hudson.slaves.DumbSlave;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public final class ExtractedSeparateClass97043 {
    private ExtractedSeparateClass97043() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod2844(final DumbSlave slave1, final DumbSlave slave2) throws InterruptedException {
        slave1.toComputer().waitUntilOnline();
        assertThat(slave1.toComputer().isOnline(), equalTo(true));
        assertThat(slave1.toComputer().getOfflineCause(), equalTo(null));
        slave2.toComputer().waitUntilOnline();
        assertThat(slave2.toComputer().isOnline(), equalTo(true));
        assertThat(slave2.toComputer().getOfflineCause(), equalTo(null));
    }
}
