
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:46:02.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [86:9~89:73]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [123:9~126:73]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [217:9~220:73]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [143:9~146:73]

*/


package hudson.cli;

import hudson.slaves.DumbSlave;
import org.jvnet.hudson.test.JenkinsRule;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public final class ExtractedSeparateClass80889 {
    private ExtractedSeparateClass80889() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static DumbSlave getSlave61367(final JenkinsRule j) throws Exception {
        DumbSlave slave = j.createSlave("aNode", "", null);
        slave.toComputer().waitUntilOnline();
        assertThat(slave.toComputer().isOnline(), equalTo(true));
        assertThat(slave.toComputer().getOfflineCause(), equalTo(null));
        return slave;
    }
}
