
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:05:43.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [95:9~97:104]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [183:9~185:105]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [180:9~182:105]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [108:9~110:104]
   test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java , [116:9~118:104]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [318:9~320:105]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [377:9~379:105]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [426:9~428:105]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [321:9~323:105]
   test/src/test/java/hudson/cli/OfflineNodeCommandTest.java , [374:9~376:105]

*/


package hudson.cli;

import hudson.slaves.DumbSlave;
import hudson.slaves.OfflineCause;
import hudson.slaves.OfflineCause.ByCLI;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.instanceOf;

public final class ExtractedSeparateClass69646 {
    private ExtractedSeparateClass69646() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod97971(final DumbSlave slave) {
        assertThat(slave.toComputer().isOffline(), equalTo(true));
        assertThat(slave.toComputer().getOfflineCause(), instanceOf(OfflineCause.ByCLI.class));
        assertThat(((OfflineCause.ByCLI) slave.toComputer().getOfflineCause()).message, equalTo(null));
    }
}
