
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:53:14.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/jenkins/security/ApiTokenPropertyTest.java , [286:9~288:75]
   test/src/test/java/jenkins/security/apitoken/ApiTokenStatsTest.java , [123:9~125:75]
   test/src/test/java/jenkins/security/apitoken/ApiTokenStatsRestartTest.java , [165:9~167:75]

*/


package jenkins.security;

import com.gargoylesoftware.htmlunit.xml.XmlPage;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.xml.HasXPath.hasXPath;

public final class ExtractedSeparateClass99273 {
    private ExtractedSeparateClass99273() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod233(final XmlPage xmlPage) {
        assertThat(xmlPage, hasXPath("//anonymous", is("false")));
        assertThat(xmlPage, hasXPath("//authenticated", is("true")));
        assertThat(xmlPage, hasXPath("//authority", is("authenticated")));
    }
}
