
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:04:17.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/jenkins/security/apitoken/ApiTokenStatsRestartTest.java , [171:9~176:10]
   test/src/test/java/jenkins/security/ApiTokenPropertyTest.java , [292:9~298:10]
   test/src/test/java/jenkins/security/apitoken/ApiTokenStatsTest.java , [129:9~134:10]

*/


package jenkins.security;

import java.io.IOException;
import com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException;
import org.jvnet.hudson.test.JenkinsRule.WebClient;
import org.xml.sax.SAXException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

public final class ExtractedSeparateClass95095 {
    private ExtractedSeparateClass95095() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod43016(final WebClient wc) throws IOException, SAXException {
        try{
            wc.goToXml("whoAmI/api/xml");
            fail();
        }
        catch(FailingHttpStatusCodeException e){
            assertEquals(401, e.getStatusCode());
        }
    }
}
