
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:05:12.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/jenkins/install/SetupWizard.java , [383:13~387:14]
   core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java , [271:9~275:10]

*/


package hudson.security;

import javax.servlet.http.HttpSession;
import org.kohsuke.stapler.StaplerRequest;

public final class ExtractedSeparateClass60172 {
    private ExtractedSeparateClass60172() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod64838(final StaplerRequest req) {
        HttpSession session = req.getSession(false);
        if (session != null) {
            // avoid session fixation
            session.invalidate();
        }
    }
}
