
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:04:06.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/test/java/hudson/FunctionsTest.java , [274:9~276:43]
   core/src/test/java/hudson/logging/LogRecorderTest.java , [93:9~95:43]

*/


package hudson;

import jenkins.model.Jenkins;
import static org.powermock.api.mockito.PowerMockito.mock;
import static org.powermock.api.mockito.PowerMockito.mockStatic;
import static org.powermock.api.mockito.PowerMockito.when;

public final class ExtractedSeparateClass49834 {
    private ExtractedSeparateClass49834() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static Jenkins getJ92619() {
        mockStatic(Jenkins.class);
        Jenkins j = mock(Jenkins.class);
        when(Jenkins.get()).thenReturn(j);
        return j;
    }
}
