
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:04:29.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/model/FileParameterValueTest.java , [406:13~410:14]
   test/src/test/java/hudson/model/DirectoryBrowserSupportTest.java , [208:13~212:14]

*/


package hudson.model;

public final class ExtractedSeparateClass74585 {
    private ExtractedSeparateClass74585() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod90471(final String initialValue) {
        if (initialValue == null) {
            System.clearProperty(DirectoryBrowserSupport.class.getName() + ".CSP");
        } else {
            System.setProperty(DirectoryBrowserSupport.class.getName() + ".CSP", initialValue);
        }
    }
}
