
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:06:51.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/model/NodeTest.java , [218:9~221:43]
   test/src/test/java/hudson/model/NodeTest.java , [247:9~250:43]
   test/src/test/java/hudson/model/UserTest.java , [474:9~477:43]
   test/src/test/java/hudson/model/UserTest.java , [392:9~395:43]
   test/src/test/java/hudson/model/UserTest.java , [493:9~496:43]
   test/src/test/java/hudson/model/ProjectTest.java , [597:9~600:43]
   test/src/test/java/hudson/model/ProjectTest.java , [635:9~638:43]
   test/src/test/java/hudson/model/ProjectTest.java , [541:9~544:43]
   test/src/test/java/hudson/model/ProjectTest.java , [670:9~673:43]

*/


package hudson.model;

import hudson.security.GlobalMatrixAuthorizationStrategy;
import hudson.security.HudsonPrivateSecurityRealm;
import org.jvnet.hudson.test.JenkinsRule;

public final class ExtractedSeparateClass90924 {
    private ExtractedSeparateClass90924() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static HudsonPrivateSecurityRealm getRealm6141(final JenkinsRule j, final GlobalMatrixAuthorizationStrategy auth) {
        j.jenkins.setAuthorizationStrategy(auth);
        j.jenkins.setCrumbIssuer(null);
        HudsonPrivateSecurityRealm realm = new HudsonPrivateSecurityRealm(false);
        j.jenkins.setSecurityRealm(realm);
        return realm;
    }
}
