
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:51:05.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/model/FileParameterValueTest.java , [393:9~397:76]
   test/src/test/java/hudson/model/DirectoryBrowserSupportTest.java , [195:9~199:76]

*/


package hudson.model;

import com.gargoylesoftware.htmlunit.html.HtmlPage;
import static org.junit.Assert.assertEquals;

public final class ExtractedSeparateClass82931 {
    private ExtractedSeparateClass82931() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static String getPropName63447(final HtmlPage page) {
        for (String header : new String[]{"Content-Security-Policy", "X-WebKit-CSP", "X-Content-Security-Policy"}) {
            assertEquals("Header set: " + header, DirectoryBrowserSupport.DEFAULT_CSP_VALUE, page.getWebResponse().getResponseHeaderValue(header));
        }
        
        String propName = DirectoryBrowserSupport.class.getName() + ".CSP";
        return propName;
    }
}
