
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:00:49.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/model/NodeTest.java , [217:9~219:40]
   test/src/test/java/hudson/model/NodeTest.java , [246:9~248:40]
   test/src/test/java/hudson/model/UserTest.java , [391:9~393:40]
   test/src/test/java/hudson/model/UserTest.java , [473:9~475:40]
   test/src/test/java/hudson/model/UserTest.java , [492:9~494:40]
   test/src/test/java/hudson/model/ProjectTest.java , [560:9~562:40]

*/


package hudson.model;

import hudson.security.GlobalMatrixAuthorizationStrategy;
import org.jvnet.hudson.test.JenkinsRule;

public final class ExtractedSeparateClass39347 {
    private ExtractedSeparateClass39347() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static GlobalMatrixAuthorizationStrategy getAuth95621(final JenkinsRule j) {
        GlobalMatrixAuthorizationStrategy auth = new GlobalMatrixAuthorizationStrategy();
        j.jenkins.setAuthorizationStrategy(auth);
        j.jenkins.setCrumbIssuer(null);
        return auth;
    }
}
