
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:01:36.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/jenkins/security/ImpersonatingExecutorService.java , [76:9~83:11]
   core/src/main/java/jenkins/security/ImpersonatingScheduledExecutorService.java , [75:9~82:11]

*/


package jenkins.security;

import java.util.concurrent.Callable;
import hudson.security.ACL;
import hudson.security.ACLContext;
import org.springframework.security.core.Authentication;

public final class ExtractedSeparateClass53431 {
    private ExtractedSeparateClass53431() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static <V> Callable<V> getVar57648(final Callable<V> r) {
        Authentication authentication = null;
        return new Callable<V>() {
            @Override
            public V call() throws Exception {
                try (ACLContext ctxt = ACL.as2(authentication)) {
                    return r.call();
                }
            }
        };
    }
}
