
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:48:14.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/jenkins/security/HMACConfidentialKey.java , [104:9~106:18]
   core/src/main/java/jenkins/security/DefaultConfidentialStore.java , [134:9~136:26]

*/


package jenkins.security;

public final class ExtractedSeparateClass9524 {
    private ExtractedSeparateClass9524() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static byte[] getB23004(final int length, final byte[] mac) {
        byte[] b = new byte[length];
        System.arraycopy(mac,0,b,0,b.length);
        return b;
    }
}
