
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:46:55.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/AbstractItemSecurity1114Test.java , [29:9~31:73]
   test/src/test/java/hudson/search/SearchTest.java , [429:9~431:55]

*/


package hudson;

import jenkins.model.Jenkins;
import org.jvnet.hudson.test.JenkinsRule;
import org.jvnet.hudson.test.MockAuthorizationStrategy;

public final class ExtractedSeparateClass92678 {
    private ExtractedSeparateClass92678() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static MockAuthorizationStrategy getAuthorizationStrategy75326(final JenkinsRule j) {
        j.jenkins.setSecurityRealm(j.createDummySecurityRealm());
        MockAuthorizationStrategy authorizationStrategy = new MockAuthorizationStrategy();
        authorizationStrategy.grant(Jenkins.READ).onRoot().toEveryone();
        return authorizationStrategy;
    }
}
