
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:02:06.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/model/ComputerConfigDotXmlTest.java , [166:9~168:65]
   test/src/test/java/hudson/cli/UpdateNodeCommandTest.java , [87:9~89:65]

*/


package hudson;

import hudson.model.Node;
import org.jvnet.hudson.test.JenkinsRule;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

public final class ExtractedSeparateClass35216 {
    private ExtractedSeparateClass35216() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod43023(final JenkinsRule rule) {
        final Node updatedSlave = rule.jenkins.getNode("SlaveFromXML");
        assertThat(updatedSlave.getNodeName(), equalTo("SlaveFromXML"));
        assertThat(updatedSlave.getNumExecutors(), equalTo(42));
    }
}
