
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:46:52.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/util/FormValidationSecurity1893Test.java , [46:9~48:108]
   test/src/test/java/hudson/markup/MarkupFormatterTest.java , [110:9~112:108]

*/


package hudson;

import com.gargoylesoftware.htmlunit.WebResponse;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;

public final class ExtractedSeparateClass1365 {
    private ExtractedSeparateClass1365() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod93096(final WebResponse response) {
        assertThat(response.getResponseHeaderValue("Content-Security-Policy"), containsString("default-src 'none';"));
        assertThat(response.getResponseHeaderValue("X-Content-Security-Policy"), containsString("default-src 'none';"));
        assertThat(response.getResponseHeaderValue("X-WebKit-CSP"), containsString("default-src 'none';"));
    }
}
