
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:02:09.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/cli/OnlineNodeCommandTest.java , [317:9~321:18]
   test/src/test/java/hudson/model/ExecutorTest.java , [169:9~173:18]

*/


package hudson;

import java.util.concurrent.Future;
import hudson.model.FreeStyleBuild;
import hudson.model.FreeStyleProject;
import hudson.util.OneShotEvent;
import static org.junit.Assert.assertTrue;

public final class ExtractedSeparateClass84563 {
    private ExtractedSeparateClass84563() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static Future<FreeStyleBuild> getR66396(final FreeStyleProject project, final OneShotEvent block) throws InterruptedException {
        Future<FreeStyleBuild> r = project.scheduleBuild2(0);
        block.block();  // wait until we are safe to interrupt
        assertTrue(project.getLastBuild().isBuilding());
        
        return r;
    }
}
