
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:49:48.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/model/ParametersTest.java , [177:9~180:48]
   test/src/test/java/hudson/model/ParametersTest.java , [140:9~143:48]
   test/src/test/java/hudson/model/ParametersTest.java , [157:9~160:48]
   test/src/test/java/hudson/model/ParametersTest.java , [54:9~56:48]
   test/src/test/java/hudson/model/ParametersTest.java , [108:9~110:48]
   test/src/test/java/hudson/cli/BuildCommandTest.java , [232:9~234:48]

*/


package hudson;

import java.io.IOException;
import hudson.model.FreeStyleProject;
import hudson.model.ParametersDefinitionProperty;
import org.jvnet.hudson.test.CaptureEnvironmentBuilder;

public final class ExtractedSeparateClass76144 {
    private ExtractedSeparateClass76144() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static CaptureEnvironmentBuilder getBuilder40267(final FreeStyleProject project, final ParametersDefinitionProperty pdb) throws IOException {
        project.addProperty(pdb);
        
        CaptureEnvironmentBuilder builder = new CaptureEnvironmentBuilder();
        project.getBuildersList().add(builder);
        return builder;
    }
}
