
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:00:39.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/slaves/AgentInboundUrlTest.java , [69:9~72:67]
   test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerTest.java , [314:9~318:67]
   test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerTest.java , [231:13~236:71]

*/


package hudson;

import jenkins.model.Jenkins;
import org.jvnet.hudson.test.JenkinsRule;
import org.jvnet.hudson.test.MockAuthorizationStrategy;

public final class ExtractedSeparateClass67130 {
    private ExtractedSeparateClass67130() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static void extractedMethod47960(final JenkinsRule r) {
        r.jenkins.setSecurityRealm(r.createDummySecurityRealm());
        
        // let anonymous user have read access
        MockAuthorizationStrategy authorizationStrategy = new MockAuthorizationStrategy();
        authorizationStrategy.grant(Jenkins.ADMINISTER).everywhere().toEveryone();
        r.jenkins.setAuthorizationStrategy(authorizationStrategy);
    }
}
