
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:06:17.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/model/QueueTest.java , [898:9~903:62]
   test/src/test/java/hudson/cli/ListJobsCommandTest.java , [102:9~107:62]

*/


package hudson;

import java.io.IOException;
import hudson.matrix.Axis;
import hudson.matrix.AxisList;
import hudson.matrix.MatrixProject;
import hudson.model.Label;
import hudson.model.labels.LabelExpression;

public final class ExtractedSeparateClass84999 {
    private ExtractedSeparateClass84999() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static Label getLabel66766(final MatrixProject matrixProject) throws IOException {
        matrixProject.setDisplayName("downstream");
        matrixProject.setAxes(new AxisList(
                new Axis("axis", "a", "b")
        ));
        
        Label label = LabelExpression.get("aws-linux-dummy");
        return label;
    }
}
