
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:47:21.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/hudson/util/ProcessTree.java , [1602:13~1605:26]
   core/src/main/java/hudson/util/ProcessTree.java , [1335:13~1338:26]

*/


package hudson.util;

public final class ExtractedSeparateClass23138 {
    private ExtractedSeparateClass23138() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static int getVar94810(final boolean IS_LITTLE_ENDIAN, final int i) {
        if(IS_LITTLE_ENDIAN)
            return (i<<24) |((i<<8) & 0x00FF0000) | ((i>>8) & 0x0000FF00) | (i>>>24);
        else
            return i;
    }
}
