
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:04:02.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/hudson/util/ProcessTree.java , [1583:17~1586:29]
   core/src/main/java/hudson/util/ProcessTree.java , [1316:17~1319:29]

*/


package hudson.util;

import java.io.ByteArrayOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

public final class ExtractedSeparateClass55097 {
    private ExtractedSeparateClass55097() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static String getLine41267(final ByteArrayOutputStream buf, final Logger LOGGER, final String prefix, final Level FINEST) {
        String line = buf.toString();
        if(LOGGER.isLoggable(FINEST))
            LOGGER.finest(prefix+" was "+line);
        return line;
    }
}
