
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:48:23.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/hudson/util/XStream2.java , [444:17~446:25]
   core/src/main/java/hudson/util/DescribableList.java , [283:17~285:25]
   core/src/main/java/hudson/util/PersistedList.java , [285:17~287:25]
   core/src/main/java/hudson/util/ProcessTree.java , [936:17~938:25]
   core/src/main/java/hudson/util/ProcessTree.java , [816:17~818:25]

*/


package hudson.util;

public final class ExtractedSeparateClass30141 {
    private ExtractedSeparateClass30141() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static IllegalAccessError getX35602(final ReflectiveOperationException e) {
        IllegalAccessError x = new IllegalAccessError();
        x.initCause(e);
        return x;
    }
}
