
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:04:12.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/hudson/util/FormFieldValidator.java , [308:13~317:28]
   core/src/main/java/hudson/util/FormValidation.java , [509:13~518:28]

*/


package hudson.util;

import java.net.URLConnection;
import java.util.Locale;

public final class ExtractedSeparateClass28745 {
    private ExtractedSeparateClass28745() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static String getVar26479(final URLConnection con) {
        for( String t : con.getContentType().split(";") ) {
            t = t.trim().toLowerCase(Locale.ENGLISH);
            if(t.startsWith("charset="))
                return t.substring(8);
        }
        // couldn't find it. HTML spec says default is US-ASCII,
        // but UTF-8 is a better choice since
        // (1) it's compatible with US-ASCII
        // (2) a well-written web applications tend to use UTF-8
        return "UTF-8";
    }
}
