
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 13-05-2021 05:02:00.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/hudson/util/FormValidation.java , [482:13~486:26]
   core/src/main/java/hudson/util/FormFieldValidator.java , [281:13~285:26]

*/


package hudson.util;

import java.io.BufferedReader;
import java.io.IOException;

public final class ExtractedSeparateClass58296 {
    private ExtractedSeparateClass58296() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static boolean isVar87845(final BufferedReader in, final String literal) throws IOException {
        String line;
        while((line=in.readLine())!=null)
            if(line.contains(literal))
                return true;
        return false;
    }
}
